package create;

/**
 * Generated by GTNH build system — contains the mod version token.
 * Do not edit manually; the build replaces GRADLETOKEN_VERSION at compile time.
 */
public class Tags {
    public static final String VERSION = "GRADLETOKEN_VERSION";
}
