package create.core.kinetic;

import create.shim.MyDirection;
import net.minecraftforge.common.util.ForgeDirection;

/**
 * Contract for tile entities that participate in the kinetic network.
 *
 * <p>Implementors must provide face connection state, speed, stress properties,
 * and position information so the BFS propagator can traverse the network.</p>
 */
public interface IKineticTile {

    /** Current rotation speed in RPM. Zero if unpowered or overstressed. */
    float getSpeed();

    /** Set the current rotation speed. Called by the propagator. */
    void setSpeed(float speed);

    /** Base stress impact at 1 RPM (consumers) or 0 (relays/sources). */
    float calculateStressApplied();

    /** Base stress capacity at 1 RPM (sources) or 0 (relays/consumers). */
    float calculateAddedStressCapacity();

    /** Whether the given face is connected to another kinetic component. */
    boolean isConnected(ForgeDirection side);

    /** Set whether the given face is connected. */
    void setConnected(ForgeDirection side, boolean connected);

    /** Returns true if this tile generates its own speed (a kinetic source). */
    boolean isSource();

    /** Speed generated by this tile, or 0 if not a source. */
    float getGeneratedSpeed();

    /** The network ID, or null if not assigned. */
    Long getNetworkId();

    /** Set the network ID. */
    void setNetworkId(Long id);

    /** The position of the tile driving this one, or null if self-powered or idle. */
    java.util.Optional<create.shim.MyBlockPos> getSourcePosition();

    /** Set the source position. */
    void setSourcePosition(create.shim.MyBlockPos pos);

    /** Clear the source and reset speed to 0. */
    void removeSource();

    /** This tile's position in the world. */
    create.shim.MyBlockPos getKineticPos();

    /** The dimension ID this tile lives in. */
    int getDimensionId();

    /** The type of kinetic block, for speed-ratio calculations. */
    KineticBlockType getKineticType();

    /** The axis this block rotates around. */
    create.shim.MyDirection.Axis getRotationAxis();

    /** True if this face is along the rotation axis (shaft-like connection). */
    default boolean hasShaftTowards(ForgeDirection face) {
        return getRotationAxis() == MyDirection.Axis.fromForge(face);
    }
}
